# Generated by Django 5.2.4 on 2025-10-17 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_administradores', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoinvitacionadminevento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='codigoinvitacionadminevento',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigos_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
