# Generated by Django 5.2.8 on 2025-11-29 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0004_remove_evento_inscripciones_habilitadas'),
        ('app_participantes', '0004_proyecto_pro_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='pro_valor',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_creados', to='app_participantes.participante'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.evento'),
        ),
    ]
