# Generated by Django 5.2.8 on 2025-11-29 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0004_remove_evento_inscripciones_habilitadas'),
        ('app_participantes', '0005_remove_proyecto_pro_valor_proyecto_creador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='creador',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='pro_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='app_eventos.evento'),
        ),
    ]
