# Generated by Django 5.2.8 on 2025-11-29 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_participantes', '0006_remove_proyecto_creador_proyecto_pro_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_creados', to='app_participantes.participante'),
        ),
    ]
