# Generated by Django 5.2.8 on 2025-11-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_participantes', '0007_proyecto_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='pro_valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
